services:
  scfr.phpbbJsonTemplate.listener:
    class: scfr\phpbbJsonTemplate\event\listener
    arguments:
      - '@template'
      - '@user'
      - '@dbal.conn'
      - '@request'
      - '@scfr.phpbbJsonTemplate.helper.api'
    tags:
      - { name: event.listener }
  scfr.phpbbJsonTemplate.helper.api:
    class: scfr\phpbbJsonTemplate\helper\api
    arguments:
      - '@template'
      - '@user'
  scfr.phpbbJsonTemplate.helper.userinfo:
    class: scfr\phpbbJsonTemplate\helper\userinfo
  scfr.phpbbJsonTemplate.helper.mp.convo:
    class: scfr\phpbbJsonTemplate\helper\mp\convo
  scfr.phpbbJsonTemplate.helper.mp.user:
    class: scfr\phpbbJsonTemplate\helper\mp\user
  scfr.phpbbJsonTemplate.controller.api.mp:
    class: scfr\phpbbJsonTemplate\controller\api\mp       
    arguments:
      - '@controller.helper'
      - '@user'
      - '@scfr.phpbbJsonTemplate.helper.api'